

const actions = {
    SET_AUTH_USER: "SET_AUTH_USER",
    FETCH_ALL_NOTES_ACTION: "FETCH_ALL_NOTES_ACTION",
    FETCH_ALL_NOTES_SUCCESS: "FETCH_ALL_NOTES_SUCCESS",
    FETCH_ALL_NOTES_FAIL: "FETCH_ALL_NOTES_FAIL",
    SPECIFIC_UPDATE_NOTE: "SPECIFIC_UPDATE_NOTE",
    DELETE_NOTE_ACTION: "DELETE_NOTE_ACTION",
    DELETE_NOTE_SUCCESS: "DELETE_NOTE_SUCCESS",
    DELETE_NOTE_FAIL: "DELETE_NOTE_FAIL"

}
export default actions